image: condaforge/mambaforge:22.9.0-1

# Commands to start on workspace startup
tasks:
  - name: install packages 
    init: mamba install -c anaconda jupyter 
    command: mamba create -n dev -c bioconda fastqc fastp kraken2 spades bowtie2 blast
  - name: install bash-notebook
    init: pip install bash_kernel
    command: python -m bash_kernel.install

vscode:
  extensions:
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - microsoft.jupyter